name: Build and Push Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup C++ Build Environment
        run: sudo apt-get install -y build-essential

      - name: Build Project
        run: |
          cd cele-8-ture
          make

      - name: Build Docker image
        run: docker build -t cele-8-ture .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PASS }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag cele-8-ture ${{ secrets.DOCKER_USERNAME }}/cele-8-ture
          docker push ${{ secrets.DOCKER_USERNAME }}/cele-8-ture

      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker tag cele-8-ture ghcr.io/${{ github.actor }}/cele-8-ture:latest
          docker push ghcr.io/${{ github.actor }}/cele-8-ture:latest